#!/usr/bin/env python3
"""
The command line interface for pysrec.
"""

import click
import os

from zwuenf.pysrec.SRecord import SRecord
from zwuenf.pysrec import SRECError

@click.group()
def cli():
    """
    Command line interface for pysrec. Use --help for details.
    """
    pass


@cli.command(
    short_help='Print Motorola S-record file.',
    help="""Print the lines of a Motorola S-Record file.""")
@click.option('--start', default=0, help='Line to start with printing. (allows python style indexing)')
@click.option('--end', default=0, help='Line to end with printing. (allows python style indexing)')
@click.option('--errors/--no-errors', default=False, help='Don\'t stop displaying the file on parsing errors.')
@click.argument('file')
def cat(start, end, errors, file):
    if not os.path.isfile(file):
        print('File: "{}", is not a file or does not exist.'.format(file))
        exit(1)

    with open(file) as f:
        lines = f.readlines()

    if end is 0:
        end = len(lines)

    for i, line in enumerate(lines[start:end]):
        try:
            click.echo(SRecord(line))
        except SRECError:
            if errors:
                print('Line could no be parsed! Try again with --no-errors to ignore errors.')
                exit(1)
            pass




@cli.command(
    short_help='Show information about a Motorola S-Record file.',
    help="""Show information about a Motorola S-Record file.""")
@click.argument('file')
def info(file):
    click.echo()
    click.echo("Not implemented yet!")


@cli.command(
    short_help='Check a Motorola S-Record file.',
    help="""Check a Motorola S-Record file for abnormality and errors.""")
@click.option('--full', help='Test file with all implemented checks.')
@click.option('--types', help='Test TYPE field for valid SX types')
@click.option('--count', help='Test COUNT field for valid byte count.')
@click.option('--addr', help='Test ADDRESS field for valid representation and length.')
@click.option('--data', help='Test DATA field for valid representation and length.')
@click.option('--crc', help='Test CRC fields.')
@click.option('--ascii', help='Test if file is in a valid ASCII representation.')
@click.argument('file')
def check(full, types, count, addr, data, crc, ascii, file):
    click.echo()
    click.echo("Not implemented yet!")


if __name__ == '__main__':
    cli()